# Don't print a new line at the start of the prompt

add_newline = false
format="""
$username[@](bold bright-white)\
$hostname\
${custom.separator}\
$shlvl\
$singularity\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$cmake\
$dart\
$elixir\
$erlang\
$golang\
$java\
$julia\
$kotlin\
$lua\
$nodejs\
$python\
$ruby\
$rust\
$nix_shell\
$custom\
$status\
$shell\
$cmd_duration\
${custom.separator}\
${custom.giturl}\
$line_break\
$time $character
"""

[character]                            # The name of the module we are configuring is "character"
error_symbol = "[∗](bold red) "
success_symbol = "[➜](bold green) "     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[username]
show_always = true
format= "[$user]($style)"
style_user = "bold bright-cyan"
style_root = "black bold"

[hostname]
format = "[$hostname]($style) "
ssh_only = false
style = "bold bright-blue"

[directory]
disabled = false
style = "bold bright-purple"

[gcloud]
disabled = true

[custom.separator]
command = "echo ' - '"
format = "$output"

[custom.giturl]
disabled = false
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL="  "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL="  "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL="  "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL="  "
else
    GIT_REMOTE_SYMBOL="  "
fi
echo "$GIT_REMOTE_SYMBOL "
"""

when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
shell = ["bash", "--noprofile", "--norc"]
format = "[$output]($style)"
style= "bright-white"


[time]
disabled = false
format="[$time]($style)"
style="bold bright-black"
